localhost ansible_connection=local

[all:vars]
cluster_name=hybrid-gitops-eks
region=ap-northeast-2
vpc_id=vpc-01cf09dc5fc6ff6c5
cluster_endpoint=https://5EE912A43C44E19BB33F1846DE82E74E.gr7.ap-northeast-2.eks.amazonaws.com
