localhost ansible_connection=local

[all:vars]
cluster_name=hybrid-gitops-eks
region=ap-northeast-2
vpc_id=vpc-0af4b9ae80eddf3cf
cluster_endpoint=https://F2E19B98D39DFD53BB4A8539226BF8CF.yl4.ap-northeast-2.eks.amazonaws.com
