apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hybrid-ai-stack
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: manifest-repo
    repoURL: https://github.com/Seungmin-Jeong2001/hybrid-ai-gitops_test.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
