apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hybrid-ai-stack
  namespace: argocd
  annotations:
    # 1. 감시할 ECR 리포지토리 지정
    argocd-image-updater.argoproj.io/image-list: model=380958218266.dkr.ecr.ap-northeast-2.amazonaws.com/ai-serving-api

    # 2. 8자리 소문자/숫자 조합의 고유 SHA 태그만 필터링
    argocd-image-updater.argoproj.io/model.allow-tags: regexp:^[a-z0-9]{8}$

    # 3. 전략: 가장 최근에 푸시된 날짜 기준으로 정렬하여 최신본 판별
    argocd-image-updater.argoproj.io/model.update-strategy: latest

    # 4. KServe 구조 분석을 위한 컨테이너 내부 경로 강제 매핑 (여러 줄 주석 규격 준수)
    argocd-image-updater.argoproj.io/model.container-images: |
      - name: kserve-container
        path: spec.predictor.containers[0]

    # 5. 변경된 고유 SHA 태그를 깃허브 파일로 기록하는 Git write-back 방식 적용
    argocd-image-updater.argoproj.io/write-back-method: git

    # 🔥 [6번 주석 신설] 앤서블이 생성해 준 깃허브 인증용 시크릿 연동
    argocd-image-updater.argoproj.io/git-repository: https://github.com/Seungmin-Jeong2001/hybrid-ai-gitops_test.git
    argocd-image-updater.argoproj.io/write-back-secret: secret:argocd/git-write-back-secret#git.password

spec:
  project: default
  source:
    repoURL: https://github.com/Seungmin-Jeong2001/hybrid-ai-gitops_test.git
    targetRevision: HEAD
    path: manifest-repo
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true