apiVersion: apps/v1
kind: Deployment
metadata:
  name: hybrid-ai-app
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: app
        image: 380958218266.dkr.ecr.ap-northeast-2.amazonaws.com/ai-serving-api:0c54b807