apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: hybrid-ai-model
  namespace: default
  annotations:
    serving.kserve.io/deploymentMode: RawDeployment
spec:
  predictor:
    minReplicas: 1
    maxReplicas: 3
    containers:
      - name: kserve-container
        image: 380958218266.dkr.ecr.ap-northeast-2.amazonaws.com/ai-serving-api:0c7346c9
        ports:
          - containerPort: 5000
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: "500m"
            memory: 512Mi