apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - isvc.yaml

# 🔥 [추가] KServe 이미지 경로 탐색을 위한 커스텀 설정 바인딩
configurations:
  - kustomize-config.yaml
